name: Test

on: 
  push:
  pull_request:

permissions: {}

jobs:
  test:
    strategy:
      matrix:
        go-version: [oldstable, stable]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Install Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
      with:
        go-version: ${{ matrix.go-version }}

    - name: Validate
      if: matrix.platform == 'ubuntu-latest'
      run: make validate

    - name: Test
      run: make test
